#!/usr/bin/env zsh

sb-upgrade() {
  # a list of the apps to upgrade
  local apps=(
    plex
    jackett
    sonarr
    radarr
  )

  for app in $apps; do
    echo "$fg_bold[blue]Upgrading $app...$reset_color"

    local app_file="/usr/bin/app-$app"
    
    # update plex to the latest version
    if test "$app" = "plex"; then
      "$app_file" upgrade --plex-version=latest
    else
      "$app_file" upgrade
    fi

    echo "$fg_bold[blue]Restarting $app...$reset_color"
    "$app_file" restart
  done

  echo "$fg_bold[green]Finished upgrades!$reset_color"
}

